name: app_review
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter.
version: 2.1.2+2
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/fluttercommunity/app_review

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  http: ^0.13.5
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreview
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
